# Generated by Django 4.2.1 on 2023-07-11 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Informatique', 'Informatique'), ('Business', 'Business'), ('Droit', 'Droit'), ('Appretissange des langues', 'Appretissange des langues')], default='Informatique', max_length=255)),
                ('photo', models.ImageField(default='photo/categories/default_cours.png', upload_to='photo/categories/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('datePub', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('fichier', models.FileField(default=None, null=True, upload_to='support//%y/%m/%d')),
                ('photo', models.ImageField(default='photo/cours/default_cours.png', upload_to='photo/cours/%y/%m/%d')),
                ('nombreEtds', models.IntegerField(default=0)),
                ('nombreChaps', models.IntegerField(default=0)),
                ('nombreQues', models.IntegerField(default=0)),
                ('avgRate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(blank=True, default=-1, null=True)),
                ('comment', models.TextField(blank=True, default='Aucun', null=True)),
                ('score', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prof.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('etd', 'etd'), ('prof', 'prof')], default='etd', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prof.user')),
                ('nom', models.CharField(default='Aucun', max_length=50)),
                ('prenom', models.CharField(default='Aucun', max_length=50)),
                ('telephone', models.CharField(blank=True, default='Aucun', max_length=10, null=True)),
                ('linkedin', models.CharField(blank=True, default='Aucun', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='Aucun', max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], default='Homme', max_length=20)),
                ('photo', models.ImageField(default='photo/user/default_user.png', upload_to='photo/etds/%y/%m/%d')),
                ('NiveauEtude', models.CharField(choices=[('sans bac', 'sans bac'), ('bac', 'bac'), ('bac+2', 'bac+2'), ('bac+3', 'bac+3'), ('bac+5', 'bac+5')], default='bac', max_length=10)),
            ],
            bases=('prof.user',),
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='prof.user')),
                ('nom', models.CharField(default='Aucun', max_length=50)),
                ('prenom', models.CharField(default='Aucun', max_length=50)),
                ('telephone', models.CharField(blank=True, default='Aucun', max_length=10, null=True)),
                ('linkedin', models.CharField(blank=True, default='Aucun', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='Aucun', max_length=100, null=True)),
                ('sexe', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], default='Homme', max_length=20)),
                ('photo', models.ImageField(default='photo/user/default_user.png', upload_to='photo/profs/%y/%m/%d')),
                ('bio', models.TextField()),
            ],
            bases=('prof.user',),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='prof.choice')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prof.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('note', models.IntegerField(default=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.course')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.question'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video/cours/%y/%m/%d', verbose_name='contenu')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prof.prof')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prof.etudiant'),
        ),
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prof.prof'),
        ),
    ]
