# Generated by Django 4.2.1 on 2023-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_alter_prof_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(default='photo/etds/default_user.jpg', upload_to='photo/etds/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='prof',
            name='photo',
            field=models.ImageField(default='photo/profs/default_user.jpg', upload_to='photo/profs/%y/%m/%d'),
        ),
    ]
