from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('error/',views.error,name='error'),
    path('courses/',views.courses,name='courses'),
    path('contact/',views.contact,name='contact'),
    path('contactUs/',views.contactUs,name='contactUs'),
    path('contactEtd/',views.contactEtd,name='contactEtd'),
    path('team/',views.team,name='team'),
    path('profil/',views.profil,name='profil'),
    path('modProfil/',views.modProfil,name='modProfil'),
    path('header/',views.testNav,name='header'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('home/',views.homeProf,name='homeProf'),
    path('ajoutCours/',views.ajoutCours,name='ajoutCours'),
    path('delAllCourses/',views.delAllCourses,name='delAllCourses'),
    path('delAllChapters/',views.delAllChapters,name='delAllChapters'),
    path('afficherCourse/',views.afficherCourse,name='afficherCourse'),
    path('modCourse/',views.modCourse,name='modCourse'),
    path('ajoutChapitre/',views.ajoutChapitre,name='ajoutChapitre'),
    path('ajoutQuestion/',views.ajoutQuestion,name='ajoutQuestion'),
    path('afficherQuestion/',views.afficherQuestion,name='afficherQuestion'),
    path('modQuestion/',views.modQuestion,name='modQuestion'),
    path('delQuestion/',views.delQuestion,name='delQuestion'),    
    path('delAllQuestions/',views.delAllQuestions,name='delAllQuestions'),    
    path('delCourse/',views.delCourse,name='delCourse'),    
    path('afficherChapitre/',views.afficherChapitre,name='afficherChapitre'),
    path('delChapitre/',views.delChapitre,name='delChapitre'),
    path('modChapitre/',views.modChapitre,name='modChapitre'),
    #***************************************************************************************************
    path('indexEtd', views.indexEtd, name='indexEtd'),
    path('nav/',views.nav,name='nav'),
    path('coursesEtd/',views.coursesEtd,name='coursesEtd'),
    path('course/', view=views.CourseListView.as_view(), name='course'),
    path('profilEtd/',views.profilEtd,name='profilEtd'),
    path('modProfilEtd/',views.modProfilEtd,name='modProfilEtd'),
    path('<int:course_id>/desinscrire/',views.desinscrit,name='desinscrire'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='course_details'),
    path('<int:course_id>/inscrit/', views.inscrit, name='inscrit'),
    path('<int:course_id>/submit/', views.submit, name='submit'),
    path('<int:course_id>/rate/',views.rate,name='rate'),
    path('course/<int:course_id>/submission/<int:submission_id>/result/', views.show_exam_result, name='show_exam_result'),
]
